Repository ofWorse/Graphika, pull requests merged in 2024-05, with the labels that each got.

#106 update paraboilc integration method #0204
  resources/pymodules/integration.py
Labels: bug

#109 clear architecture: make a clean architecture for the best developmen…
  Graphika.pro
  drawable.h
  expressionvalidator.cpp
  graphbuilder.ui
  interfaces.h
  layoutfactory.cpp
  layoutfactory.h
  mainwindow.ui
  src/app/head/algs/compositestatestack.h
  src/app/head/algs/expressionvalidator.h
  src/app/head/algs/graphbuilder.h
  src/app/head/algs/pythonconveyor.h
  src/app/head/algs/reportpdfgenerator.h
  src/app/head/algs/stringparser.h
  src/app/head/settings/settings.h
  src/app/head/ui/leftwidget.h
  src/app/head/ui/mainwindow.h
  src/app/head/ui/menu.h
  src/app/head/ui/rightwidget.h
  src/app/head/ui/toolbar.h
  src/app/head/utils/buffer.h
  src/app/head/utils/errorhandler.h
  src/app/head/utils/graphInfo.h
  src/app/head/utils/mathutils.h
  src/app/head/utils/sender.h
  src/app/head/utils/validatestring.h
  src/app/impl/algs/compositestatestack.cpp
  src/app/impl/algs/graphbuilder.cpp
  src/app/impl/algs/pythonconveyor.cpp
  src/app/impl/algs/reportpdfgenerator.cpp
  src/app/impl/algs/stringparser.cpp
  src/app/impl/include/mathutils.cpp
  src/app/impl/main.cpp
  src/app/impl/ui/leftwidget.cpp
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/menu.cpp
  src/app/impl/ui/rightwidget.cpp
  src/app/impl/ui/toolbar.cpp
  src/app/impl/utils/buffer.cpp
  src/app/impl/utils/mathutils.cpp
  src/app/impl/utils/sender.cpp
  src/app/impl/utils/validatestring.cpp
  src/app/main.cpp
  src/include/settings.h
Labels: task

#118 clean code: first iteration of clear code base. Fix mainwindow & tool…
  Graphika.pro
  src/app/head/ui/mainwindow.h
  src/app/head/ui/toolbar.h
  src/app/head/ui/wgts/leftwidget.h
  src/app/head/ui/wgts/oper/operationstrategy.h
  src/app/head/ui/wgts/rightwidget.h
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/toolbar.cpp
  src/app/impl/ui/wgts/leftwidget.cpp
  src/app/impl/ui/wgts/oper/operationstrategy.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
  src/app/impl/utils/mathutils.cpp
Labels: task

#119 clean code: rollback changes toolbar #0201
  src/app/head/ui/toolbar.h
  src/app/impl/ui/toolbar.cpp
Labels: task

#121 about: add about sheet and gplv3 license #0209
  Graphika.pro
  icons.qrc
  referenceinfo.qrc
  resources/about.PNG
  resources/aboutSheet.bin
  resources/authors.PNG
  resources/fdl-1.3.txt
  src/app/head/ui/mainwindow.h
  src/app/head/ui/menu.h
  src/app/head/ui/menu/sheetmenu.h
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/menu.cpp
  src/app/impl/ui/menu/sheetmenu.cpp
Labels: task

#122 resources/pymodules add documentation notes to all modules
  resources/pymodules/differentiation.py
  resources/pymodules/integration.py
  resources/pymodules/laes_solver.py
  resources/pymodules/polynomials.py
Labels: task

#123 pythonconveyor: optimize code #0201
  src/app/head/algs/pythonconveyor.h
  src/app/impl/algs/pythonconveyor.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
  src/app/impl/utils/sender.cpp
Labels: task

#125 pythonconveyor: fix #0201
  src/app/head/algs/pythonconveyor.h
Labels: bug

#127 graphbuilder: fixed a bug with moving the legend №0208
  Graphika.pro.user
  src/app/impl/algs/graphbuilder.cpp
Labels: bug

#128 graphbuilder: The initializer has been fixed, coordinates are now dis…
  Graphika.pro.user
  src/app/head/algs/graphbuilder.h
  src/app/impl/algs/graphbuilder.cpp
Labels: bug

#129 pythonconveyor: add documentation #0211
  src/app/head/algs/pythonconveyor.h
  src/app/impl/algs/pythonconveyor.cpp
Labels: documentation, task

#130 graphbuilder: added the ability to save graphs in png and jpg #0205
  Graphika.pro.user
  src/app/head/algs/graphbuilder.h
  src/app/head/ui/mainwindow.h
  src/app/head/ui/wgts/rightwidget.h
  src/app/impl/algs/graphbuilder.cpp
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/toolbar.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
Labels: task

#132 graphbuilder: fix #0213
  Graphika.pro.user
  src/app/head/algs/graphbuilder.h
  src/app/impl/algs/graphbuilder.cpp
Labels: bug

#133 graphbuilder: fix bug with graphs, add app scalability and add indent…
  src/app/head/algs/expressionvalidator.h
  src/app/head/algs/pythonconveyor.h
  src/app/head/utils/graphInfo.h
  src/app/impl/algs/graphbuilder.cpp
  src/app/impl/algs/pythonconveyor.cpp
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/toolbar.cpp
  src/app/impl/ui/wgts/leftwidget.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
Labels: bug, task

#134 graphbuilder: Documentation has been completed №0211
  Graphika.pro.user
  src/app/head/algs/graphbuilder.h
  src/app/head/ui/wgts/rightwidget.h
  src/app/impl/algs/graphbuilder.cpp
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
Labels: documentation

#137 graphbuilder: fixt image saving algoritm #0213
  Graphika.pro.user
  src/app/head/algs/graphbuilder.h
  src/app/impl/algs/graphbuilder.cpp
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/wgts/rightwidget.cpp
Labels: task

#138 fix: fixed bugs + documentation #0214
  Graphika.pro.user
  src/app/head/ui/wgts/lwgt/derivationlayout.h
  src/app/head/ui/wgts/lwgt/equationslayout.h
  src/app/head/ui/wgts/lwgt/functionlayout.h
  src/app/head/ui/wgts/lwgt/integrationlayout.h
  src/app/head/ui/wgts/lwgt/layoutInitializer.h
  src/app/head/ui/wgts/lwgt/polynomialslayout.h
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/menu.cpp
  src/app/impl/ui/menu/sheetmenu.cpp
  src/app/impl/ui/wgts/leftwidget.cpp
  src/app/impl/ui/wgts/lwgt/derivationlayout.cpp
  src/app/impl/ui/wgts/lwgt/equationslayout.cpp
  src/app/impl/ui/wgts/lwgt/functionlayout.cpp
  src/app/impl/ui/wgts/lwgt/integrationlayout.cpp
  src/app/impl/ui/wgts/lwgt/layoutInitializer.cpp
  src/app/impl/ui/wgts/lwgt/polynomialslayout.cpp
Labels: bug

#139 fix: fixed some bugs + authors menu #0214
  Graphika.pro.user
  icons.qrc
  referenceinfo.qrc
  resources/authors.jpg
  resources/authors.svg
  resources/beirut.PNG
  resources/icons.qrc
  src/app/head/ui/mainwindow.h
  src/app/impl/ui/mainwindow.cpp
  src/app/impl/ui/menu.cpp
  src/app/impl/ui/menu/sheetmenu.cpp
  src/app/impl/ui/toolbar.cpp
Labels: bug
